# Generated by Django 6.0.6 on 2026-06-27 07:06

from django.db import migrations

def create_roles(apps, schema_editor):

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    view_prod = Permission.objects.get(codename='view_product')
    add_prod = Permission.objects.get(codename='add_product');
    change_prod = Permission.objects.get(codename='change_product');
    delete_prod = Permission.objects.get(codename='delete_product');

    view_cat = Permission.objects.get(codename='view_category');
    add_cat = Permission.objects.get(codename='add_category');
    change_cat = Permission.objects.get(codename='change_category');
    delete_cat = Permission.objects.get(codename='delete_category');

    view_sup = Permission.objects.get(codename='view_supplier');
    add_sup = Permission.objects.get(codename='add_supplier');
    change_sup = Permission.objects.get(codename='change_supplier');

    view_stock = Permission.objects.get(codename='view_stockmovement');
    add_stock = Permission.objects.get(codename='add_stockmovement');
    change_stock = Permission.objects.get(codename='change_stockmovement');
    delete_stock = Permission.objects.get(codename='delete_stockmovement');

    staff_group, _ = Group.objects.get_or_create(name='Staff')
    staff_group.permissions.set([view_prod, view_stock, add_stock, change_stock, delete_stock])

    manager_group, _ = Group.objects.get_or_create(name='Manager')
    manager_group.permissions.set([view_prod, add_prod, change_prod, delete_prod, view_cat, add_cat, change_cat, delete_cat, view_sup, add_sup, change_sup, view_stock, add_stock, change_stock, delete_stock])

def remove_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Staff', 'Manager']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles, reverse_code=remove_roles)
    ]
