# Generated by Django 6.0.6 on 2026-06-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_catalog_pro_created_92b554_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
